add github actions
start-jsk/jsk_apc pull request #2745
Opened 2021-06-26 07:16 UTC by knorth55

add github actions

2021-06-26 18:08 UTC, knorth55 commented
all test passed!

2021-06-28 05:57 UTC, knorth55 commented
@pazeshun I add github actions for faster CI than travis CI.
we do not run several tests in github actions, and we run whole tests in travis CI.
what do you think?

Another issue is that we want to support noetic for the near future.
I started doing the integration in #2746, but we have to wait to upstream repositories.

2021-06-28 09:30 UTC, pazeshun commented
> @pazeshun I add github actions for faster CI than travis CI.
> we do not run several tests in github actions, and we run whole tests in travis CI.
> what do you think?

I think it's OK.
Thank you very much for heavy installation!!!

>     * exclude `instance_occlsegm` and `grasp_fusion` test because of gdrive download maximum trials

Just out of curiosity, is this actually avoidable by using cache?
https://dev.to/github/caching-dependencies-to-speed-up-workflows-in-github-actions-3efl
Anyway, we currently have no time to use this, and travis targeting master branch is enough, I think.

2021-06-28 09:32 UTC, pazeshun requested changes

2021-06-28 09:32 UTC, pazeshun commented on .github/workflows/indigo.yaml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
```suggestion
      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkout .travis submodules
```

2021-06-28 09:37 UTC, pazeshun commented on .github/workflows/indigo.yaml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
Oh, I understand this is copied from jsk_travis.
Perhaps we should leave it as it is.
I'll follow @knorth55 's thought.

2021-06-28 09:39 UTC, knorth55 commented
@pazeshun thanks.

>Just out of curiosity, is this actually avoidable by using cache?
https://dev.to/github/caching-dependencies-to-speed-up-workflows-in-github-actions-3efl
Anyway, we currently have no time to use this, and travis targeting master branch is enough, I think.

I will take a look later.

2021-06-28 09:40 UTC, pazeshun commented on .github/workflows/indigo.yaml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
@knorth55 コメントが間に合わず申し訳ないんですが、前のコメントの通り、typoそのままでもいいかなと思っています。

2021-06-28 10:07 UTC, knorth55 commented on .github/workflows/indigo.yaml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
typoだしなおしておきましょう

2021-06-28 10:16 UTC, pazeshun requested changes

2021-06-28 10:16 UTC, pazeshun commented on .github/workflows/indigo.yaml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkout .travis submodule
```suggestion
      - name: Install latest git (use sudo for ros-ubuntu, remove sudo for ubuntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkout .travis submodules
```

2021-06-28 10:16 UTC, pazeshun commented on .github/workflows/indigo.yaml
> +      - name: Before Checkout # need for actoins/checkout with ros-ubuntu container
```suggestion
      - name: Before Checkout # need for actions/checkout with ros-ubuntu container
```

2021-06-28 10:16 UTC, pazeshun commented on .github/workflows/kinetic.yml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
```suggestion
      - name: Install latest git (use sudo for ros-ubuntu, remove sudo for ubuntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkout .travis submodules
```

2021-06-28 10:16 UTC, pazeshun commented on .github/workflows/kinetic.yml
> +      - name: Before Checkout # need for actoins/checkout with ros-ubuntu container
```suggestion
      - name: Before Checkout # need for actions/checkout with ros-ubuntu container
```

2021-06-28 10:16 UTC, pazeshun commented on .github/workflows/melodic.yml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
```suggestion
      - name: Install latest git (use sudo for ros-ubuntu, remove sudo for ubuntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkout .travis submodules
```

2021-06-28 10:16 UTC, pazeshun commented on .github/workflows/melodic.yml
> +      - name: Before Checkout # need for actoins/checkout with ros-ubuntu container
```suggestion
      - name: Before Checkout # need for actions/checkout with ros-ubuntu container
```

2021-06-28 10:17 UTC, pazeshun commented on .github/workflows/indigo.yaml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
了解です、他にもtypo見つけてしまったのでreviewしておきました。
jsk_travis本家にもPR送っておきます。

2021-06-28 10:22 UTC, pazeshun commented on .github/workflows/indigo.yaml
> +      - name: Install latest git ( use sudo for ros-ubuntu, remove sudo for ubntu container), checkout@v2 uses REST API for git<2.18, which removes .git folder and does not checkkout .travis submodul
> jsk_travis本家にもPR送っておきます。

よく見たら既にPR出ていました。
https://github.com/jsk-ros-pkg/jsk_travis/pull/430

2021-06-28 10:26 UTC, knorth55 commented
@pazeshun I fixed the typos before your suggestions.

2021-06-28 10:30 UTC, pazeshun commented
> @pazeshun I fixed the typos before your suggestions.

Oops, I overlooked this. Sorry...

2021-06-28 10:45 UTC, knorth55 commented
github action cache does not work properly because of permission error.

https://github.com/ros-tooling/setup-ros-docker/issues/7
https://github.com/actions/cache/issues/404

2021-06-29 15:27 UTC, knorth55 commented
I comment out github actions cache

2021-06-29 17:05 UTC, pazeshun approved these changes
Thank you very much!!!

2021-06-30 02:13 UTC, merged